### ISSUE TITLE
Failed to install node-krb5 while deployment in OpenShift

### ISSUE THREAD

**Issue by tkdchen** [onepiecejs/nodejs-cantas#126]
```
Error: Cannot find module 'node-krb5'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /var/lib/openshift/55882f985973ca02c2000190/app-root/runtime/repo/services/auth
/strategies.js:21:14
    at Object.<anonymous> (/var/lib/openshift/55882f985973ca02c2000190/app-root/runtime/repo/services/auth/strategies.js:166:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
DEBUG: Program node app.js exited with code 8
DEBUG: Starting child process with 'node app.js'
```

@xiaods how did you overcome this issue when you deployed current workable instance in OpenShift, Is there any workaround?

**Comment by xiaods** [comment]
i have remove node-krb5 in openshift script.
